using System.ComponentModel.DataAnnotations;

namespace Andy.Agentic.Domain.Entities;

/// <summary>
///     Represents an exported document generated by the document export tool.
/// </summary>
public class DocumentExportEntity
{
    /// <summary>
    ///     Unique identifier for the exported document.
    /// </summary>
    [Key]
    public Guid Id { get; set; }

    /// <summary>
    ///     Title of the exported document.
    /// </summary>
    [Required]
    [MaxLength(255)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    ///     Format of the exported document (excel, pdf, word).
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string Format { get; set; } = string.Empty;

    /// <summary>
    ///     File name of the exported document.
    /// </summary>
    [Required]
    [MaxLength(500)]
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    ///     Binary content of the exported document.
    /// </summary>
    [Required]
    public byte[] Content { get; set; } = Array.Empty<byte>();

    /// <summary>
    ///     Size of the document in bytes.
    /// </summary>
    public long Size { get; set; }

    /// <summary>
    ///     UTC timestamp when the document was exported.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    ///     Foreign key referencing the user who created this export (optional).
    /// </summary>
    public Guid? CreatedByUserId { get; set; }

    /// <summary>
    ///     Navigation property to the user who created this export.
    /// </summary>
    public virtual UserEntity? CreatedByUser { get; set; }

    /// <summary>
    ///     Foreign key referencing the agent that generated this export (optional).
    /// </summary>
    public Guid? AgentId { get; set; }

    /// <summary>
    ///     Navigation property to the agent that generated this export.
    /// </summary>
    public virtual AgentEntity? Agent { get; set; }

    /// <summary>
    ///     Foreign key referencing the session where this export was generated (optional).
    /// </summary>
    [MaxLength(255)]
    public string? SessionId { get; set; }
}

